name: Publish

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout quartz template repo
        uses: actions/checkout@v2
        with:
          repository: awannabeengineer/quartz
          path: ./

      - name: Checkout notes
        uses: actions/checkout@v2
        with:
          repository: awannabeengineer/wbe
          path: ./content

      - name: Housekeeping
        run: |
          mv content/notes/Index.md content/_index.md

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v1.0.2
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo --minify --gc
          mv config.toml ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
