name: Publish

permissions: write-all

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout quartz template repo
        uses: actions/checkout@v3
        with:
          repository: awannabeengineer/quartz
          path: ./

      - name: Checkout notes
        uses: actions/checkout@v3
        with:
          repository: awannabeengineer/wbe
          token: ${{ secrets.GH_PAT }}
          path: ./content

      - name: Get latest obsidian-export
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'awannabeengineer/obsidian-export'
          file: 'obsidian-export'

      - name: Run obsidian-export script
        run: |
          ls
          chmod +x obsidian-export
          mkdir ./exported-notes
          ./obsidian-export raw_notes ./exported-notes --hard-linebreaks --no-recursive-embeds --hugo-frontmatter
        continue-on-error: true

      - name: Housekeeping
        run: |
          mv exported-notes content
          rm -rf raw_notes
          rm -rf exported-notes


      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.19
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo --minify --gc
          mv config.toml ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
